# Generated by Django 5.2.3 on 2025-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chatbot/audio/'),
        ),
    ]
